spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veritabani_adi
    username: kullanici_adi
    password: sifre
  jpa:
    hibernate:
      ddl-auto: update

# Swagger ayarları
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
